require "nokogiri"
require "open-uri"
require "httparty"
require "net/http"
require "pry"
require "tty-prompt"
require "colorize"
require "artii"
require "dotenv"
Dotenv.load

require_relative "./planner/version"
require_relative "./planner/api"
require_relative "./planner/cli"
require_relative "./planner/meal"
require_relative "./planner/ingredient"
require_relative "./planner/mealscraper"
